### ISSUE TITLE
The operation couldn’t be completed https://instance.my.salesforce.com/services/data/v39.0/sobjects/objectName error 411

### ISSUE THREAD

**Issue by runconsultantsra** [forcedotcom/SalesforceMobileSDK-CordovaPlugin#402]
I am getting this error when trying to create a salesforce object using the iOS mobileSDK, version 5.3.0.  Query works fine, it's just create that is failing.

"The operation couldn’t be completed https://instance.my.salesforce.com/services/data/v39.0/sobjects/objectName__c error 411"

This same code use to work.  The only change is pointing to a new sandbox (changing SFDCOAuthLoginHost in xCode).  My javascript code calls force.create(), which abstracts all of the HTTP plumbing.

force.create( "objectName__c", myJsonData, success, error);

Is this an HTTP 411 error?  If so, does the iOS mobileSDK 5.3.0 send content-length with the object create request?

**Comment by bhariharan** [comment]
We have fixed this in a newer version of Mobile SDK. Please install Mobile SDK 6.1 and try this.

**Comment by runconsultantsra** [comment]
I am still seeing the same issue in Mobile SDK 6.1:
"The operation couldn’t be completed. (https://dot--stage.my.salesforce.com/services/data/v42.0/sobjects/DSR__c error 411.)"

Any insight?  Possibly a Salesforce backend configuration?

**Comment by runconsultantsra** [comment]
Did you try the Mobile SDK version 6.1 with the Salesforce Summer_2018 backend release?  If I test the Mobile SDK version 5.3 or 6.1 with the current Salesforce production environment, they work.  This '411' error only occurs in the Salesforce Summer_2018 backend release, which is currently my sandbox backend environment.
